# Ejercicio de edades e ingresos
* generar una matriz 3x3 de edades entre 20 y 50 años
* generar una matriz 3x3 de ingresos entre 2000 y 5000 miles de pesos
* unir la data uno a uno en una matriz de 9x2
* filtrar aquellas filas cuya edad está entre 20 y 30 años y cuyos ingresos estan entre 2000 y 5000



In [1]:
import numpy as np

In [42]:
edades = np.random.uniform(
    low=20,
    high=50,
    size=(3,3)
).round()
edades

array([[41., 21., 24.],
       [46., 36., 33.],
       [48., 24., 23.]])

In [6]:
ingresos = np.random.uniform(
    low=2000,
    high=5000,
    size=(3,3)
).round()
ingresos

array([[3555., 4242., 4364.],
       [2475., 4453., 2643.],
       [4750., 2757., 3722.]])

In [43]:
edades_r = edades.reshape(9)
ingresos_r = ingresos.reshape(9)
union = np.column_stack((edades_r, ingresos_r))
display(
    edades_r,
    ingresos_r,
    union,
    union.shape
)

array([41., 21., 24., 46., 36., 33., 48., 24., 23.])

array([3555., 4242., 4364., 2475., 4453., 2643., 4750., 2757., 3722.])

array([[  41., 3555.],
       [  21., 4242.],
       [  24., 4364.],
       [  46., 2475.],
       [  36., 4453.],
       [  33., 2643.],
       [  48., 4750.],
       [  24., 2757.],
       [  23., 3722.]])

(9, 2)

In [44]:
edades_mayor = edades >= 20
edades_menor = edades <= 30
edades_and = np.logical_and(edades_mayor, edades_menor)
display(
    edades_mayor,
    edades_menor,
    edades_and
)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

array([[False,  True,  True],
       [False, False, False],
       [False,  True,  True]])

array([[False,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [46]:
ingresos_mayor = ingresos >= 2000
ingresos_menor = ingresos <= 5000
ingresos_and = np.logical_and(ingresos_mayor, ingresos_menor)
display(
    ingresos_mayor,
    ingresos_menor,
    ingresos_and
)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
filtro_and = np.logical_and(edades_and, ingresos_and)
filtro_r = filtro_and.reshape(9)
filtro_r

array([False,  True,  True, False, False, False, False,  True,  True])

In [83]:
union[filtro_r]

array([[  21., 4242.],
       [  24., 4364.],
       [  24., 2757.],
       [  23., 3722.]])